import './styles/style.css'
import './styles/navbar.css'
import './styles/hero.css'
import './styles/fonts.css'
import './styles/subcription.css'
import './styles/animation_logo.css'
import './styles/featured.css'